### ISSUE TITLE
Maintainance of the community builder

### ISSUE THREAD

**Issue by Mic92** [winterqt/darwin-build-box#27]
Dear winter,
I hope you are doing well. We got information that you are currently taking a break from community work. We would like to continue the community builder and keep adding more people to it.
In nix-community we have a multiple active [admins](https://github.com/nix-community/infra/blob/master/docs/administrators.md) that can take care of keeping the infrastructure running and responding to user requests. We also would have a spare darwin builder that can pick up the users that are currently in this repository. If you are ok with procedure, I would propose the following:

1. Transfer of this repository to nix-community
2. We migrate the user from this repository into one of our existing darwin builder
3. We update the repository to update let people know about the new host
4. Than we can decide what we can do with the current hardware

Let me know what you think!
Thanks.

**Comment by winterqt** [comment]
That would be great.

Let me know when you want me to transfer the repo etc.

**Comment by Mic92** [comment]
Any time you want. You can initiate the transfer as you are already part of this organization.

**Comment by winterqt** [comment]
Should be all set now, though GitHub warns of some caching for the next few minutes.

**Comment by Mic92** [comment]
We already started the process on our side as well: https://github.com/nix-community/infra/pull/900

**Comment by zowoq** [comment]
`darwin-build-box.nix-community.org` has been deployed.

Existing users have accounts:
@0x4A6F
@artturin
@dotlambda
@emilylange
@fabaff
@figsoda
@mweinelt
@julienmalka
@k900
@lilyinstarlight
@ma27
@phaer
@raitobezarius
@stephank
@toonn
@winterqt 

I've also added these accounts from the pending PRs.
@delroth
@emilytrau
@Janik-Haag

**Comment by GaetanLepage** [comment]
Hello ! I had also open a [PR](https://github.com/nix-community/darwin-build-box/pull/28) to get access. Would it be possible to be added as well ?

**Comment by zowoq** [comment]
> Hello ! I had also open a [PR](https://github.com/nix-community/darwin-build-box/pull/28) to get access. Would it be possible to be added as well ?

Sorry, I started working on this a couple of weeks ago and forgot to check for new PRs. Added in https://github.com/nix-community/infra/pull/912.

**Comment by zowoq** [comment]
> 4. Than we can decide what we can do with the current hardware

Hetzner seems to have plenty of macos stock lately so I think if we do need another machine it'll be easy enough for us to get one.  Can cancel this machine, we don't need to transfer it.

cc @Mic92 @zimbatm

**Comment by winterqt** [comment]
Assuming both Jörg and Jonas echo your sentiment (it seems reasonable to me), I'll go ahead and initiate the cancellation. I don't think it'll go through until January, though, which gives people more time to see this issue.

**Comment by Mic92** [comment]
> Assuming both Jörg and Jonas echo your sentiment (it seems reasonable to me), I'll go ahead and initiate the cancellation. I don't think it'll go through until January, though, which gives people more time to see this issue.

Yes. Fine with me.

**Comment by zimbatm** [comment]
Sounds good

**Comment by Mic92** [comment]
This is now complete.
